### ISSUE TITLE
Mixed Python Environments

### ISSUE THREAD

**Issue by Legends0** [ansible-ThoTeam/nexus3-oss#203]
I am running a different python on my remote host than my localhost. Python on the localhost does not match python on the remote host.

As a result, this task fails:
```
- name: Archive scripts
  become: no
  archive:
    path: "{{ role_path }}/files/groovy/*"
    dest: "/tmp/nexus-upload-groovy-scripts.tar.gz"
  run_once: true
  delegate_to: localhost
```

My workaround is to add vars to the task.
```
vars:
      ansible_python_interpreter: python
```
