### ISSUE TITLE
Error when trying to unarchive new scripts

### ISSUE THREAD

**Issue by cryptomatt** [ansible-ThoTeam/nexus3-oss#229]
My scenario:

Trying to run nexus3-oss role in a packer script to build an AWS AMI. The base AMI is Centos 7

Most of the role works fine till it reaches 

```
- name: Upload new scripts
  unarchive:
    src: "/tmp/nexus-upload-groovy-scripts.tar.gz"
    dest: "{{ nexus_data_dir }}/groovy-raw-scripts/new/"

```

at this point ansible errors out saying 

```
    amazon-ebs: TASK [ansible-ThoTeam.nexus3-oss : Unarchive new scripts] **********************
    amazon-ebs: fatal: [default]: FAILED! => {"changed": false, "msg": "Failed to find handler for \"~mathew/.ansible/tmp/ansible-tmp-1577735084.21-174577674937181/source\". Make sure the required command to extract the file is installed. Command \"unzip\" not found. Command \"/bin/gtar\" could not handle archive."}
```

I then changed this to a regular copy using the following and that works and the rest of the role passes without incident (except ofcourse the email configuration issue with the latest version of nexus)

```
  - name: Copy scripts
    copy:
      src: "{{ item }}"
      dest: "{{ nexus_data_dir }}/groovy-raw-scripts/new/"
    with_fileglob:
    - "{{ role_path }}/files/groovy/*"
```

Have you or others seen this error before? I have searched in google and in incidents where they have observed this error, the recommendation has been to copy. I have installed unzip as well in the AMI but even that doesnt help with error. It just says unzip could not handle archive.

would it be easier if the archive and unarchive were changed to a copy step instead. The files themselves arent large and transferring them uncompressed shouldnt be that much a concern?
