### ISSUE TITLE
Apply defaults to maven proxy repos pt2

### ISSUE THREAD

**Issue by mbotmcc** [ansible-ThoTeam/nexus3-oss#237]
When running the role I get the following error:

> TASK [ansible-thoteam.nexus3-oss : apply defaults to maven proxy repos] ******************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'mvn'\n\nThe error appears to be in '/root/.ansible/roles/ansible-thoteam.nexus3-oss/tasks/process_repos_list.yml': line 12, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: apply defaults to maven proxy repos\n  ^ here\n"}

Playbook: 

```
---
- name: Nexus
  hosts: localhost
  become: yes

  vars:
    nexus_timezone: 'GMT'
    nexus_admin_password: "..." #"{{ vault_nexus_admin_password }}"
    nexus_privileges:
      - name: all-repos-read
        description: 'Read & Browse access to all repos'
        repository: '*'
        actions:
          - read
          - browse
    nexus_blob_names:
      pypi:
        blob: 'default'
    nexus_anonymous_access: true
    nexus_delete_default_repos: true
    nexus_backup_configure: true
    nexus_backup_cron: '0 0 21 * * ?'  # See cron expressions definition in nexus create task gui
    nexus_backup_dir: '/var/nexus-backup'
    nexus_backup_dir_create: true
    nexus_restore_log: '{{ nexus_backup_dir }}/nexus-restore.log'
    nexus_backup_rotate: false
    nexus_backup_rotate_first: false
    nexus_backup_keep_rotations: 4  # Keep 4 backup rotation by default (current + last 3)
    nexus_config_pypi: true
    
    _nexus_repos_pypi_defaults:
      blob_store: "{{ nexus_blob_names.pypi.blob }}"
      strict_content_validation: true
      version_policy: release  # release, snapshot or mixed
      layout_policy: strict  # strict or permissive
      write_policy: allow_once  # one of "allow", "allow_once" or "deny"
      maximum_component_age: 1440  # Nexus gui default. For proxies only
      maximum_metadata_age: 1440  # Nexus gui default. For proxies only
      negative_cache_enabled: true  # Nexus gui default. For proxies only
      negative_cache_ttl: 1440  # Nexus gui default. For proxies only
    nexus_repos_pypi_proxy:
    - name: pypi
      remote_url: 'https://pypi.python.org/'


  roles:
    
    
    - { role: geerlingguy.java }
    # Debian/Ubuntu only
    # - { role: geerlingguy.apache, apache_create_vhosts: no, apache_mods_enabled: ["proxy.load", "proxy_http.load", "headers.load"], apache_remove_default_vhost: true, tags: ["geerlingguy.apache"] }
    # RedHat/CentOS only
    # - { role: geerlingguy.apache, apache_create_vhosts: no, apache_remove_default_vhost: true, tags: ["geerlingguy.apache"] }
    - { role: ansible-thoteam.nexus3-oss, tags: ['ansible-thoteam.nexus3-oss'] }
```
