### ISSUE TITLE
"Blob store groups are not enabled" when configuring S3 blobstores

### ISSUE THREAD

**Issue by chrobotm** [ansible-ThoTeam/nexus3-oss#238]
Trying to create a s3 blob but am getting this error:

>_TASK [ansible-thoteam.nexus3-oss : Calling Groovy script create_blobstores_from_list] **************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "connection": "close", "content_length": "284", "content_type": "application/json", "cookies": {}, "cookies_string": "", "date": "Fri, 24 Jan 2020 11:35:35 GMT", "elapsed": 0, "failed_when_result": true, "json": {"name": "create_blobstores_from_list", "result": "{\"changed\":false,\"error\":true,\"action_details\":[{\"name\":\"s3-blobstore\",\"type\":\"S3\",\"status\":\"error\",\"error_msg\":\"org.sonatype.nexus.rest.ValidationErrorsException: Blob store groups are not enabled\"}]}"}, "msg": "OK (284 bytes)", "redirected": false, "server": "Nexus/3.20.1-01 (OSS)", "status": 200, "url": "http://localhost:8081/service/rest/v1/script/create_blobstores_from_list/run", "x_content_type_options": "nosniff"}_

Looking at the documentation, blob store groups are only supported in the pro version but I'm not specifying a group in the playbook just a single blob store. This works fine manually via the console.

Playbook:

```
---
- name: Nexus
  hosts: localhost
  become: yes

  vars:
    nexus_timezone: 'GMT'
    nexus_admin_password: "..." #"{{ vault_nexus_admin_password }}"
    nexus_privileges:
      - name: all-repos-read
        description: 'Read & Browse access to all repos'
        repository: '*'
        actions:
          - read
          - browse
    nexus_anonymous_access: true
    nexus_delete_default_repos: true
    nexus_backup_configure: true
    nexus_backup_cron: '0 0 21 * * ?'  # See cron expressions definition in nexus create task gui
    nexus_backup_dir: '/var/nexus-backup'
    nexus_backup_dir_create: true
    nexus_restore_log: '{{ nexus_backup_dir }}/nexus-restore.log'
    nexus_backup_rotate: false
    nexus_backup_rotate_first: false
    nexus_backup_keep_rotations: 4  # Keep 4 backup rotation by default (current + last 3)
    nexus_config_pypi: true
    nexus_blobstores:
      - name: s3-blobstore
        type: S3
        config:
          bucket: mybucket
    nexus_repos_pypi_proxy:
    - name: pypi-proxy
      remote_url: 'https://pypi.org/'
      blob_store: s3-blobstore

  roles:
    - { role: geerlingguy.java }
    - { role: ansible-thoteam.nexus3-oss, tags: ['ansible-thoteam.nexus3-oss'] }
```
