### ISSUE TITLE
Issue deleting docker repo created with role

### ISSUE THREAD

**Issue by thorsteinbn** [ansible-ThoTeam/nexus3-oss#251]
I'm having an interesting issue. When trying to delete docker related repository (I have not tested other types, so I'm unsure if this is a general issue or just a docker repo issue), I get an error message in the Nexus GUI and need to restart the entire server.

This only happens with repos created with this role, manually created repos from the GUI works fine and can be deleted. 

The config used is as follows:

```
_nexus_repos_docker_defaults:
  blob_store: "{{ nexus_blob_names.docker.blob }}"
  force_basic_auth: true
  strict_content_validation: true
  version_policy: release  # release, snapshot or mixed
  layout_policy: strict  # strict or permissive
  write_policy: allow_once  # one of "allow", "allow_once" or "deny"
  maximum_component_age: 1440  # Nexus gui default. For proxies only
  maximum_metadata_age: 1440  # Nexus gui default. For proxies only
  negative_cache_enabled: true  # Nexus gui default. For proxies only
  negative_cache_ttl: 1440  # Nexus gui default. For proxies only
  # More about Foreign Layers https://help.sonatype.com/repomanager3/formats/docker-registry/foreign-layers
  cache_foreign_layers: false  # Nexus gui default. For proxies only
  foreign_layer_url_whitelist: []  # Nexus gui default. For proxies only

nexus_repos_docker_proxy:
  - name: official-docker-proxy
    use_nexus_certificates_to_access_index: false
    v1_enabled: false
    index_type: "HUB"
    remote_url: "https://registry-1.docker.io"
    use_nexus_certificates_to_access_index: false
    force_basic_auth: false

nexus_repos_docker_group:
  - name: docker-public
    fqdn: "REMOVED"
    v1_enabled: false
    force_basic_auth: false
    member_repos:
      - official-docker-proxy
    http_port: "9085"
```

Error in Nexus Logs:

2020-02-25 11:14:07,988+0000 ERROR [qtp1735228132-193]  admin org.sonatype.nexus.extdirect.internal.ExtDirectExceptionHandler - Failed to invoke action method: coreui_Repository.readReferences, java-method: org.sonatype.nexus.coreui.RepositoryComponent.readReferences
org.sonatype.nexus.common.stateguard.InvalidStateException: Invalid state: DELETED; allowed: [STARTED]

I am using the latest version of the role with Nexus version 3.21.1-01 (although I had the same issue with 3.19 as well)
