### ISSUE TITLE
Role initally fails with `nexus_delete_default_blobstore` and incomplete `nexus_blob_names`.

### ISSUE THREAD

**Issue by kevfoerster** [ansible-ThoTeam/nexus3-oss#255]
The task `Deleting default blobstore` fails the first time a playbook is executed, when the following conditions are met:
- `nexus_delete_default_blobstore: true` 
- `nexus_blob_split: false`
- Not all formats are given to `nexus_blob_names`.

The error message is "'dict object' ha no attribute 'bower'" if e. g. bower is not given as a format in `nexus_blob_names`.

Rerunning the complete playbook then works flawlessly. Example `playbook.yml`:

```yaml
---
- name: Nexus
  hosts: nexus
  become: yes

  vars:
    java_packages:
      - openjdk-8-jdk
    nexus_delete_default_repos: true
    nexus_delete_default_blobstore: true
    nexus_blobstores:
      - name: foo
        path: /var/nexus/blobs/foo
      - name: bar
        path: /var/nexus/blobs/bar

    nexus_blob_split: false
    nexus_blob_names:
      apt:
        blob: 'foo'
      yum:
        blob: 'bar'

  roles:
    - { role: geerlingguy.java }
    - { role: ansible-thoteam.nexus3-oss, tags: ['ansible-thoteam.nexus3-oss'] }
```
