### ISSUE TITLE
Resources are not get updated or deleted based on code/variables changes.

### ISSUE THREAD

**Issue by 5obol** [ansible-ThoTeam/nexus3-oss#288]
Play:
```
---
- name: Nexus
  hosts: nexus
  vars:
    nexus_version: '3.22.0-02'
    nexus_version_running: '3.22.0-02'
    nexus_roles:
      - id: Developpers-ansible1 # maps to the LDAP group
        name: developers-ansible1-edited
        description: All developers edited
        privileges:
          - nx-search-read
        roles: []
    nexus_blobstores:
      - name: company-artifacts-updated
        path: /var/nexus/blobs/company-artifacts
    nexus_repos_maven_hosted:
      - name: company-project-updated-2
        version_policy: mixed
        write_policy: allow
        blob_store: company-artifacts-updated
    nexus_local_users:
      - username: jenkins-ansible1 # used as key to update
        first_name: Jenkins-ansible1-edited-2
        last_name: CIEdited
        state: present # default value if ommited, use 'absent' to remove user
        email: support@company.com
        password: "s3cr3t"
        roles:
          - Developpers-ansible1 # role ID here
  roles:
    - { role: nexus3-oss }
```
Issues description/clarification:
Issue with updating of the resources:
- When we change repository name, it just creates new one. Without touching old one.
  Expected behaviour: either re-create or change in-place if possible.
- When we update values for User it doesn't reflect at all. Nothing happens.
The same update behaviour for roles. 
Issue with deleting of the resources:
When we fully delete values - nothing happens. 
Expected behaviour: resources get deleted. It applies (this issue) to roles/users/repositories.
