### ISSUE TITLE
Docker Error https://nexus/v2/ failed with status: 404 Not Found when ssl enable, but docker port not configure

### ISSUE THREAD

**Issue by patsevanton** [ansible-ThoTeam/nexus3-oss#299]
Hello! Thanks for nexus3-oss
```
docker login https://nexus
Username: user1
Password: 
Error response from daemon: login attempt to https://nexus/v2/ failed with status: 404 Not Found
```

vars:
```
  vars:
    nexus_public_scheme: https
    nexus_anonymous_access: true
    nexus_public_hostname: 'nexus'
    httpd_setup_enable: true
    httpd_server_name: "{{ nexus_public_hostname }}"
    httpd_default_admin_email: "admin@example.com"
    httpd_ssl_certificate_file: 'files/cert.crt'
    httpd_ssl_certificate_key_file: 'files/key.key'
    httpd_copy_ssl_files: true
```

![Снимок экрана от 2020-06-23 11-30-53](https://user-images.githubusercontent.com/10828883/85364534-27017800-b545-11ea-952e-c4482e7a1b24.jpg)

HTTPD Logs:
```
10.233.47.193 - - [23/Jun/2020:08:20:19 +0300] "GET /v2/ HTTP/1.1" 404 2071
10.233.47.193 - - [23/Jun/2020:08:20:19 +0300] "GET /v2/ HTTP/1.1" 404 2071
```
