### ISSUE TITLE
Facing issue when creating helm type repository using the playbook

### ISSUE THREAD

**Issue by komalkumbh** [ansible-ThoTeam/nexus3-oss#321]
Hi,

I'm trying to create a **helm type repository(proxy & hosted)** using the playbook by passing following input:
```
nexus_config_helm: true
#Create helm hosted repository
nexus_repos_helm_hosted:
  - name: helm-hosted
#Create helm proxy repository
nexus_repos_helm_proxy:
  - name: helm-proxy
    remote_url: https://remote.repository.com
```
Output:
* Role started to execute their task and completed successfully, but helm type repository not created in Nexus.
* After investigation, i saw that role is not going to the task [**Process definitions for helm repositories**], [**apply defaults to helm proxy repos**]

Following are the logs: 
_TASK [ansible-thoteam.nexus3-oss : Add apt repositories to global repos list] ***
08:14:03  task path: /users/kube/.ansible/roles/ansible-thoteam.nexus3-oss/tasks/process_repos_list.yml:448
08:14:03  skipping: [nexus_host] => {
08:14:03      "changed": false, 
08:14:03      "skip_reason": "Conditional result was False"
08:14:03  }
08:14:03  Read vars_file 'cfg/adminpass.txt'
08:14:03  Read vars_file 'cfg/ldapuserpass.txt'
08:14:03  
08:14:03  TASK [ansible-thoteam.nexus3-oss : Create configured repositories] *************
08:14:03  task path: /users/kube/.ansible/roles/ansible-thoteam.nexus3-oss/tasks/main.yml:138_

Can anyone tell me is there anything missing from my end, which needs to be passed in the playbook?

Role & Version: ansible-thoteam.nexus3-oss : v2.4.14
Nexus Version: 3.29.2-02
