### ISSUE TITLE
When re-provisioning, the role should wait for Nexus to become available

### ISSUE THREAD

**Issue by mykelalvis-rialtic** [ansible-ThoTeam/nexus3-oss#329]
The role requires access to the API endpoint ( `Access scripts API endpoint with defined admin password`)

However, it is possible that the endpoint won't be available if you are applying the role for a second time, as Nexus takes a while to start servicing it's port (default 8081)

An ***initial provision*** takes long enough for Nexus to be live before proceeding, but reprovisioning appears to be capable of not taking long enough.

It appears that either a sleep  or some sort wait-for-service call.

**Comment by mykelalvis-rialtic** [comment]
I solved this by putting these lines immediately before [this line](https://github.com/ansible-ThoTeam/nexus3-oss/blob/master/tasks/nexus_install.yml#L432)


```
- name: Wait for port 
  wait_for:
      port: "{{ nexus_api_port}}"

- name: Sleep for a bit
  pause: 
    seconds: 5
```
It works as long as you're configuring `127.0.0.1`

No clue why the pause was necessary, but I needed to wait > 3 seconds after the `wait_for` or it didn't work.
