### ISSUE TITLE
SSL proxy does not configure docker endpoints

### ISSUE THREAD

**Issue by scaganoff** [ansible-ThoTeam/nexus3-oss#34]
I tried switching on docker support using the switch:

nexus_config_docker: true

That successfully created a docker group, docker hosted and docker proxy repos, listening on ports 9080, 9081 and 9082.

However, I cannot access the docker repos using docker client without SSL. It seems we either have to enable SSL on the nexus server directly, or configure Apache to forward docker requests.

As far as I can tell, the httpd config for the vhost has not changed at all to accomodate docker repos.

Am I missing something, or does the httpd configuration need to be augmented for docker support?

Note, I have found documentation for a similar setup using HAproxy: http://www.sonatype.org/nexus/2016/06/29/using-nexus-3-as-a-private-docker-registry/

**Comment by zeitounator** [comment]
Hi @scaganoff.

The reverse proxy config in this role is currently only taking care off the default nexus url. I am planning to add support for docker connectors in a later release.

For time being, you either have to manually switch the docker connectors to ssl (and add the corresponding certificate(s) in nexus) or setup an ssl reverse proxy by yourself. An other (bad) option is to declare insecure registries in docker configuration.

I currently overcome this limitation on production with a children role inheriting this one and taking care of configuring apache as an ssl endpoint proxiing to the corresponding docker ports. I actually use it also for configuring the default reverse proxy for nexus as I need a custom configuration adapted to my client's network ecosystem (several RPs to go through....)

I added a `fqdn` parameter for each docker registry I want to config in the yaml file and I loop other all registries with this task:
```yaml
- name: Setup vhosts for each docker registry
  template:
    src: "docker-ssl-reverse-vhost_each.conf.j2"
    dest: "/etc/httpd/conf.d/docker-reverse-{{ item.fqdn }}.conf"
  with_items:
    - "{{ nexus_repos_docker_hosted }}"
    - "{{ nexus_repos_docker_proxy }}"
    - "{{ nexus_repos_docker_group }}"
  when: item.fqdn is defined
  notify:
    - httpd-service-reload
    - wait-for-httpd
```

Here is the relevant part of the template I'm using for this. 
```ApacheConf
<VirtualHost *:443>
  ServerName "{{ item.fqdn }}"

  SSLEngine on
  SSLCertificateFile /etc/pki/tls/certs/{{ item.fqdn }}.crt
  SSLCertificateKeyFile /etc/pki/tls/private/{{ item.fqdn }}.key
  SSLCertificateChainFile /etc/pki/tls/certs/{{ item.fqdn }}.crt

  ProxyPass / http://localhost:{{ item.http_port }}{{ nexus_default_context_path }}
  ProxyPassReverse / http://localhost:{{ item.http_port }}{{ nexus_default_context_path }}
  RequestHeader set X-Forwarded-Proto "https"

  ErrorLog /var/log/httpd/ssl_{{ item.fqdn }}_error_log
  CustomLog /var/log/httpd/ssl_{{ item.fqdn }}_access_log common
</VirtualHost>
```

As said above, I'm planning to introduce this as part of the role in a future relase, as well as allowing for customized reverse proxy configurations to adapt to more complex network scenarios.

Hope this helps.

**Comment by scaganoff** [comment]
Thanks @zeitounator I was able to manually create an extra VirtualHost for the docker repo. I agree that this seems the better option out of those available.

One thing I found is that the original nexus VirtualHost stops matching and I had to replace the wildcard in each case with an explicit hostname. E.g.

<VirtualHost nexus.example.com:443> 
...
</VirtualHost>

<VirtualHost docker.example.com:443> 
...
</VirtualHost>

That is what I came up with my limited httpd knowledge.

**Comment by zeitounator** [comment]
Unless you have several ips on your server and entries in your /etc/hosts file to map to names, this should not at all be necessary. Moreover, you generally use an ip rather than an fqdn there. You should check that you don't have a default ssl catchall vhost in your apache config which would be loaded before your specific vhosts. That would explain why you need this trick.

**Comment by zeitounator** [comment]
Hi @scaganoff,

Just to let you know I decided to add this feature to the next role release scheduled for next month. Cheers.

**Comment by zeitounator** [comment]
After carrefully reviewing pros and cons, I decided that this role should be kept simple. If you need a particular setup for httpd even out of docker, chances are you will have to turn off the very simple httpd config on this role and make your own. This is actually how I do it since I have to adapt to clients network topology (existing reverse proxies, different access zones, etc.....) and usually cannot rely on a  base vhost configuration (as proposed in this role).

**Comment by jeeftor** [comment]
So if I want to us docker and SSL I need to do one of these manual tweaks as explained here?  correct?

**Comment by zeitounator** [comment]
#209 introduced a new var to ease this. So very basically, running with the lastest version of the role:

* Add the fqn + port in the needed docker configs as shown above
* Create the needed certs and key files (in `files` subfolder, same level as playbook, named after fqdn)
* Create the needed template(s) (in `template` subfolder, same level as playbook, example for docker above, you can copy the template in the role for your main vhost config as a start)
* And a typical playbook would  look like this (just for example, needs modification and tests). 
```yaml
---
- name: My nexus install
  hosts: my_nexus_host_or_group
  become: true

  vars:
    # Your needeed configuration + following vars
    httpd_setup_enable: false
    nexus_application_host: 127.0.0.1
  
  roles:
    # Whichever role you choose to install java8 here
    # Whichever role you choose to install apache here 
    - role:  ansible-thoteam.nexus3-oss

  tasks:
    # Make sure httpd is installed and enabled

    - name: Create reverse proxy for main url (gui + repo access + api)
      template:
        src: my_main_vhost_template.j2
        dest: /etc/httpd/conf.d/0-my_main_vhost.conf
      notify:
        - httpd-service-reload
        - wait-for-httpd

    - name: Create reverse proxies for docker registries
        template:
          src: "docker-ssl-reverse-vhost_each.conf.j2"
          dest: "/etc/httpd/conf.d/docker-reverse-{{ item.fqdn }}.conf"
        with_items:
          - "{{ nexus_repos_docker_hosted }}"
          - "{{ nexus_repos_docker_proxy }}"
          - "{{ nexus_repos_docker_group }}"
        when: item.fqdn is defined
        notify:
          - httpd-service-reload
          - wait-for-httpd
```

* For clarity and maintenance, your can move the needed tasks along with the files and templates above to a child role inheriting from nexus3-oss (add dependency in meta/main.yml in the role).

Does this fully answers your question ?
