### ISSUE TITLE
Failed to validate facets on Docker Registry creation

### ISSUE THREAD

**Issue by CHSchuepfer** [ansible-ThoTeam/nexus3-oss#349]
Hey everyone,

im currently trying to get our nexus installation automated via Gitlab & Ansible.
For that we use your model which is 🔥 🔥 🔥 

Im currently stubling over an error.
Here is the output from my pipeline:

### Error:
```
        {
            "error_msg": "org.sonatype.goodies.common.MultipleFailures$MultipleFailuresException: Failed to validate facets; 1 failure",
            "format": "docker",
            "name": "docker-proxy",
            "status": "error",
            "type": "proxy"
        },
        {
            "error_msg": "org.sonatype.goodies.common.MultipleFailures$MultipleFailuresException: Failed to validate facets; 1 failure",
            "format": "docker",
            "name": "k1-docker-quay-proxy",
            "status": "error",
            "type": "proxy"
        },
        {
            "error_msg": "org.sonatype.goodies.common.MultipleFailures$MultipleFailuresException: Failed to validate facets; 1 failure",
            "format": "docker",
            "name": "k1-docker-ghcr-io-proxy",
            "status": "error",
            "type": "proxy"
        },
        {
            "format": "docker",
            "name": "docker-hosted",
            "status": "no change",
            "type": "hosted"
        },
        {
            "error_msg": "org.sonatype.goodies.common.MultipleFailures$MultipleFailuresException: Failed to validate facets; 1 failure",
            "format": "docker",
            "name": "docker-group",
            "status": "error",
            "type": "group"
        }
```

Here is the part of my playbook which contains the declaration:

<br>

### Playbook extract:

```
_nexus_repos_docker_defaults:
  force_basic_auth: true
  strict_content_validation: true
  version_policy: release  # release, snapshot or mixed
  layout_policy: strict  # strict or permissive
  write_policy: allow_once  # one of "allow", "allow_once" or "deny"
nexus_repos_docker_hosted:
  - name: docker-hosted
    blob_store: separate-storage
    http_port: "{{ nexus_docker_hosted_port }}"
    v1_enabled: True
nexus_repos_docker_proxy:
  - name: docker-proxy
    http_port: "{{ nexus_docker_proxy_port }}"
    v1_enabled: True
    index_type: "HUB"
    remote_url: "https://registry-1.docker.io/"
    use_nexus_certificates_to_access_index: false
  - name: k1-docker-quay-proxy
    http_port: "{{ nexus_docker_proxy_port }}"
    v1_enabled: True
    index_type: "REGISTRY"
    remote_url: "https://quay.io/"
    use_nexus_certificates_to_access_index: false
  - name: k1-docker-ghcr-io-proxy
    http_port: "{{ nexus_docker_proxy_port }}"
    v1_enabled: True
    index_type: "REGISTRY"
    remote_url: "https://ghcr.io/v2/"
    use_nexus_certificates_to_access_index: false
nexus_repos_docker_group:
  - name: docker-group
    blob_store: separate-storage
    http_port: "{{ nexus_docker_group_port }}"
    v1_enabled: True
    member_repos:
      - docker-hosted
      - docker-proxy
      - k1-docker-quay-proxy
      - k1-docker-ghcr-io-proxy
```

But i cant, for the life of me, figure out what causes the "Failed to validate facets" Error.

Any idea what i've done wrong?

Thanks in Advance and so long
