### ISSUE TITLE
Add support for specifying the NuGet version on NuGet Proxy repos

### ISSUE THREAD

**Issue by MikeCantCode** [ansible-ThoTeam/nexus3-oss#355]
Example config:
```yml
nexus_repos_nuget_proxy:
  - name: chocolatey-proxy
    blob_store: s3-blobstore
    remote_url: https://community.chocolatey.org/api/v2/
    nuget_version: v2
```

Update to `create_repos_from_list.groovy`
```groovy
// Configs for nuget proxy repos
        if (currentRepo.type == 'proxy' && currentRepo.format == 'nuget') {
            configuration.attributes['nugetProxy'] = [
                    nugetVersion: currentRepo.nuget_version.toUpperCase()
            ]
        }
```
