### ISSUE TITLE
systemd nexus service not starting on selinux enabled system

### ISSUE THREAD

**Issue by eb6143** [ansible-ThoTeam/nexus3-oss#364]
First of all thanks for such a well develop ansible role, really got us running nexus in no time. 👍 

Currently there is one failing step on a selinux enabled system (RHEL8) when running the install for the first time.

I am no selinux pro, but it seems the selinux context is not set to allow execution of the nexus binary.

task file: `nexus_install.yml`
task name: `Enable nexus systemd service and make sure it is started`
possible fix: run selinux command `chcon -R -t bin_t {{ nexus_installation_path }}/bin/nexus`
possible module run:

```yaml
- name: Allow nexus systemd service to be executable
  community.general.sefcontext:
    target: "{{ nexus_installation_path }}/bin/nexus"
    setype: bin_t
    state: present
```

Maybe someone with more experience can check if that change does make sense and is correctly implemented from OS view.
