### ISSUE TITLE
question - set authentication (user+pw) for docker proxy repo

### ISSUE THREAD

**Issue by eb6143** [ansible-ThoTeam/nexus3-oss#369]
A question regarding configuring a docker proxy repo with HTTP-auth parameters: how is this done?

I am not a groovy / java expert, but have recognized that there is a section `['httpclient']['authentication']` in the script `create_repos_from_list.groovy`.

So I have tried to include the parameters into variables file like this:

```yaml
nexus_repos_docker_proxy:
  - name: docker-proxy-with-http-auth
    index_type: "REGISTRY"
    remote_url: "foo"
    use_nexus_certificates_to_access_index: false
    type: username
    username: "user"
    password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      1234567890....
```

When running the role to update the repositories, unfortunately no http-auth parameters are set in the GUI.

Is this not implemented?
Or if it is, what is the structure of the yaml-object?

Thanks in advance. :)

**Comment by zeitounator** [comment]
If you hare read the scrict, you probably noticed that the parameter used in the passed json payload is `remote_username` as can be seen in the below code extract taking care of setting authentications:
https://github.com/ansible-ThoTeam/nexus3-oss/blob/3925e65d0dcb0d57086af53131d85b889da5da21/files/groovy/create_repos_from_list.groovy#L118-L124

Moreover, there are examples of setting a remote authentication:
- In the Blobstore and repositories section as well as in the example playbook in `README.md`
    https://github.com/ansible-ThoTeam/nexus3-oss/blob/3925e65d0dcb0d57086af53131d85b889da5da21/README.md?plain=1#L619-L627
  https://github.com/ansible-ThoTeam/nexus3-oss/blob/3925e65d0dcb0d57086af53131d85b889da5da21/README.md?plain=1#L1016-L1019
- In the `defaults/main.yml` role file
    https://github.com/ansible-ThoTeam/nexus3-oss/blob/d01b338185ff3cca4b95625fac552b0a5b0279ce/defaults/main.yml#L315-L323

So the actual expected configuration is in your specific case is:
```yaml
nexus_repos_docker_proxy:
  - name: docker-proxy-with-http-auth
    index_type: "REGISTRY"
    remote_url: "foo"
    use_nexus_certificates_to_access_index: false
    type: username
    remote_username: "user"
    remote_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      1234567890....
```
