### ISSUE TITLE
External Role Mapping

### ISSUE THREAD

**Issue by LavBU** [ansible-ThoTeam/nexus3-oss#377]
Hi,

When connecting Nexus to Azure LDAP and defining specific LDAP group, the only way to login with an LDAP user that is a member of that LDAP group is when that LDAP group is defined in Nexus Roles as "External Role Mapping".

The thing is that using Ansible, I don't see a Role setting for "External Role Mapping" but just for "Nexus Role".
For example:
```
nexus_roles:
      - id: Developpers # can map to a LDAP group id, also used as a key to update a role
        name: developers
        description: All developers
        privileges:
          - nx-search-read
          - all-repos-read
        roles: [] # references to other role names
```
Can you please advise how to use Ansible play for "External Role Mapping" Role?

Thanks,
Lavi
