### ISSUE TITLE
S3 blobstore forcepathstyle var in config

### ISSUE THREAD

**Issue by platonisation** [ansible-ThoTeam/nexus3-oss#381]
Hi all,

Thanks for the great work. 
I am sharing this here, not as an issue but in case it helps someone. It could maybe be added to the readme, otherwise closed is fine.

When using a private S3 blobstore endpoint which is not AWS compatible, you can use Nexus's forcePathStyle var, but it is not to be used with capital letters like accessKeyId or secretAccesKey. However it is quite strange because in their webAPI it is using capital letters.

For example, will **not** work:
```
      nexus_blobstores:
        - name: bla
          type: S3
          config:
            bucket: bla
            forcePathStyle: "True"
            accessKeyId: bla
            secretAccessKey: bla
            endpoint: https://bla:1234
            region: "default"
```

For example, will work:
```
      nexus_blobstores:
        - name: bla
          type: S3
          config:
            bucket: bla
            forcepathstyle: "True"
            accessKeyId: bla
            secretAccessKey: bla
            endpoint: https://bla:1234
            region: "default"
```

Regards,
