### ISSUE TITLE
Creating password protected Docker Proxy registries

### ISSUE THREAD

**Issue by Thulium-Drake** [ansible-ThoTeam/nexus3-oss#415]
Hi there!

We need to integrate container images from an external password protected registry. In the Nexus WebUI I can configure the credentials needed in the section below:

![image](https://github.com/ansible-ThoTeam/nexus3-oss/assets/12935477/e31e6913-474d-4992-a2e0-38cb590aa4fe)

However, I was not able to find a means in the scripting the role provides to do this. Is this supported? If so, how? :-)

If not, what should be changed to make it work?

**Comment by brianveltman** [comment]
Hi @Thulium-Drake 

You can set the `remote_username` and `remote_password` properties on your docker proxy repo definition. Like this:

```yaml
nexus_repos_docker_proxy:
  - name: some-docker-proxy
    blob_store: docker-blob
    remote_url: https://some-private-registry.dev/
    remote_username: 'secret-username'
    remote_password: "{{ vault_alfresco_secret_password }}"
```
Note that currently only Username is supported for authentication type. Windows NTLM is not support at this time.
