### ISSUE TITLE
Too many repos are created.

### ISSUE THREAD

**Issue by BartWillems** [ansible-ThoTeam/nexus3-oss#44]
Currently, maven repositories are always created.

It's also not possible to create only a proxy repo for instance

**Comment by zeitounator** [comment]
Hi @BartWillems, and thanks for your interest !

If you do not touch the defaults, I agree:
- Nexus will keep it's default example repos
- Maven is configured and will create 2 proxies (for central and jboss), a public group with those proxies and a private-release hosted repository. This was historically used as a default example when installing the role. I might reconsider this default behavior in a future release, as well as the possibility to totally disable maven configuration

Meanwhile, you have a total control other this from the vars you load in your playbook. If you just need, e.g. a single maven proxy instance without any group to serve public repos, you could have a maven variables like the following in your playbook:

```yaml
nexus_delete_default_repos: true
nexus_repos_maven_group: []
nexus_repos_maven_hosted: []
nexus_repos_maven_proxy:
  - name: my_single_proxy_instance
    remote_url: "https://some.maven.repo/"
```
