### ISSUE TITLE
Stuck at handler "wait-for-nexus"

### ISSUE THREAD

**Issue by araujonelson** [ansible-ThoTeam/nexus3-oss#66]
Hello.

I'm currently having an issue where the process is stuck at "wait-for-nexus" handler.

This is my playbook (it's simple as I'm just testing first)

```
 ---
 - name: Nexus
   hosts: nexus
   become: yes
 
   vars:
     nexus_admin_password: "admin"
 
   roles:
     - { role: ansible-ThoTeam.nexus3-oss, tags: ['savoirfairelinux.nexus3-oss'] }

```
And the output where it gets stuck:

```
RUNNING HANDLER [ansible-ThoTeam.nexus3-oss : wait-for-nexus] ************************************************************************************************
 Monday 16 April 2018  16:48:37 -0300 (0:00:10.410)       0:04:19.080 **********
 Using module_utils file /Library/Python/2.7/site-packages/ansible/module_utils/_text.py
 Using module_utils file /Library/Python/2.7/site-packages/ansible/module_utils/basic.py
 Using module_utils file /Library/Python/2.7/site-packages/ansible/module_utils/six/__init__.py
 Using module_utils file /Library/Python/2.7/site-packages/ansible/module_utils/parsing/convert_bool.py
 Using module_utils file /Library/Python/2.7/site-packages/ansible/module_utils/parsing/__init__.py
 Using module_utils file /Library/Python/2.7/site-packages/ansible/module_utils/pycompat24.py
 Using module file /Library/Python/2.7/site-packages/ansible/modules/utilities/logic/wait_for.py
 <10.1.1.85> ESTABLISH SSH CONNECTION FOR USER: ubuntu
 <10.1.1.85> SSH: ansible.cfg set ssh_args: (-o)(StrictHostKeyChecking=no)(-o)(ControlPath=none)
 <10.1.1.85> SSH: ANSIBLE_PRIVATE_KEY_FILE/private_key_file/ansible_ssh_private_key_file set: (-o)(IdentityFile="../terraform/ssh_keys/awstools-key")
 <10.1.1.85> SSH: ansible_password/ansible_ssh_pass not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
 <10.1.1.85> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User=ubuntu)
 <10.1.1.85> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
 <10.1.1.85> SSH: PlayContext set ssh_common_args: (-o)(ProxyCommand=ssh -i ../terraform/ssh_keys/awstools-key -W %h:%p -q ubuntu@<public-ip-removed> -o StrictHostKeyChecking=no UserKnownHostsFile=/dev/null)
 <10.1.1.85> SSH: EXEC ssh -vvv -o StrictHostKeyChecking=no -o ControlPath=none -o 'IdentityFile="../terraform/ssh_keys/awstools-key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o 'ProxyCommand=ssh -i ../terraform/ssh_keys/awstools-key -W %h:%p -q ubuntu@<public-ip-removed> -o StrictHostKeyChecking=no UserKnownHostsFile=/dev/null' 10.1.1.85 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-nxnsrkoiykmcfgazabmiiztixljtcpaz; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
```

All I can see in the handler file provided by you is:

```
 - name: wait-for-nexus
   wait_for:
     path: "{{ nexus_data_dir }}/log/nexus.log"
     search_regex: "Started Sonatype Nexus OSS .*"
     timeout: 1800
```

Tried to find that nexus.log but couldn't locate it.

Thank you in advanced,
